multipart:
    maxFileSize: 1024KB
    maxRequestSize: 512KB

spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/courrierdb?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: courrierroot
        password: courrierroot
        hikari:
            data-source-properties:
                cache-prep-stmts: true
                prep-stmt-cache-size: 250
                prep-stmt-cache-sql-limit: 2048
                use-server-prep-stmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy

    jmx:
        enabled: false
    thymeleaf:
        mode: XHTML
        cache: false
        suffix: .html
       # prefix: /WEB-INF/templates/
    devtools:
      restart:
        exclude: templates/**
        enabled: true

server:
  port: 8084
  context-path: /courrier



