multipart:
    maxFileSize: 1024KB
    maxRequestSize: 512KB

spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/courrierdb?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        username: courrierroot
        password: courrierroot
        hikari:
            data-source-properties:
                cache-prep-stmts: true
                prep-stmt-cache-size: 250
                prep-stmt-cache-sql-limit: 2048
                use-server-prep-stmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        properties:
            hibernate:
                cache:
                   use_second_level_cache: true
                   use_query_cache: false
                   region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                generate_statistics: true

        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy

    jmx:
        enabled: false
    thymeleaf:
        mode: XHTML
        cache: false
        suffix: .html
       # prefix: /WEB-INF/templates/
    devtools:
      restart:
        exclude: templates/**
        enabled: true






server:
  port: 8084
  context-path: /courrier

# ===================================================================
# JHipster specific properties
# ===================================================================

courrier:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
            timeToLiveSeconds: 3600
            ehcache:
                maxBytesLocalHeap: 16M
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    mail:
        from: hello@localhost
    swagger:
        title: hello API
        description: hello API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
